### ISSUE TITLE
Delete a batch not working

### ISSUE THREAD

**Issue by jainhere** [CodingParkFunSeries/RMS-backend#8]
I have sent the following DELETE request :

https://ajyarms.azurewebsites.net/schools/1/batches/1

After that when I call GET request, 

https://ajyarms.azurewebsites.net/schools/1/batches/

Still, it is returning Batch 1 under School 1

**Comment by ajay109458** [comment]
Delete requests are most of the controllers is not yet implemented.  I will add that.

**Comment by jainhere** [comment]
Okay
